Genymotion orb [semver:minor]
Genymobile/genymotion-saas-orb pull request #1
Opened 2020-03-30 10:02 UTC by thomascarpentier

This PR is the first ever orb in order to integrate Genymotion Cloud SaaS and CircleCI.

2020-04-09 08:11 UTC, lilinor requested changes

2020-04-09 08:11 UTC, lilinor commented on src/@orb.yml
> +  Start instances, connect through adb and stop instances on Genymotion Cloud SaaS platform.
```suggestion
Start Genymotion Android virtual device, connect through adb and stop device on Genymotion Cloud SaaS platform for mobile automation testing
```

2020-04-09 08:11 UTC, lilinor commented on src/examples/test.yml
> +description: >
Modify the name of the file to start_stop.yml

2020-04-09 08:11 UTC, lilinor commented on src/examples/test.yml
> +   Start Android instance, test your app and stop instance on Genymotion Cloud SaaS platform
```suggestion
   How to :
   - Configure your Genymotion Cloud SaaS account
   - Start Android instance, test your app and stop instance
```

2020-04-09 08:11 UTC, lilinor commented on src/examples/test.yml
> +    genymotion-saas: genymotion/genymotion-saas@dev:alpha
```suggestion
    genymotion-saas: genymotion/genymotion-saas@x.y
```
We could put the name of release version, instead of x.y

2020-04-09 08:11 UTC, lilinor commented on src/examples/test.yml
> +            recipe_uuid: "" # Mandatory: Retrieve an recipe uuid using command line gmsaas recipes list.
```suggestion
            recipe_uuid: "" # Mandatory: Retrieve the recipe uuid using 'gmsaas recipes list' command line.
```

2020-04-09 08:11 UTC, lilinor commented on src/examples/test.yml
> +            adb_serial_port: "" # Optional: Enter a specific adb serial port here or the default will use a random generated port.
```suggestion
            adb_serial_port: "" # Optional: Enter a specific adb serial port here otherwise a random port is generated.
```

2020-04-09 08:11 UTC, lilinor commented on src/commands/setup.yml
> +  Download gmsaas cli and authentificate the user
```suggestion
  Download gmsaas cli and authenticate the user
```

2020-04-09 08:11 UTC, lilinor commented on src/commands/setup.yml
> +      name: Authentificate
```suggestion
      name: Authenticate
```

2020-04-09 08:11 UTC, lilinor commented on src/commands/start-instance.yml
> +    description: recipe UUID
```suggestion
    description: Device template to use. The recipe UUID can be retrieved with command line 'gmsaas recipes list'
```

2020-04-09 08:11 UTC, lilinor commented on src/commands/start-instance.yml
> +
```suggestion
description: Adb serial port to use when the instance is connected to adb
```

2020-04-09 08:11 UTC, lilinor commented on src/commands/stop-instance.yml
> +    description: Instance UUID you want to stop.
```suggestion
    description: Instance to stop. The ID of the instance to stop is automatically retrieved. No need to set manually.
```

2020-04-09 08:11 UTC, lilinor commented on src/executors/default.yml
> +  genymotion-saas orb needs Android so we will use CircleCI's Android convenience image:
```suggestion
  Android SDK tools are required for this orb, so we will use Circle CI image for Android
```

2020-04-09 08:11 UTC, lilinor commented on README.md
> +# <orb-name> Orb [![CircleCI Build Status](https://circleci.com/gh/<org-name>/<repo-name>.svg?style=shield "CircleCI Build Status")](https://circleci.com/gh/<org-name>/<repo-name>) [![CircleCI Orb Ve
```suggestion
# genymotion-saas Orb [![CircleCI Build Status](https://circleci.com/gh/<org-name>/<repo-name>.svg?style=shield "CircleCI Build Status")](https://circleci.com/gh/<org-name>/<repo-name>) [![CircleCI Orb Version](https://img.shields.io/badge/endpoint.svg?url=https://badges.circleci.io/orb/<orb-namespace>/<orb-name>)](https://circleci.com/orbs/registry/orb/<orb-namespace>/<orb-name>) [![GitHub License](https://img.shields.io/badge/license-MIT-lightgrey.svg)](https://raw.githubusercontent.com/<org-name>/<repo-name>/master/LICENSE) [![CircleCI Community](https://img.shields.io/badge/community-CircleCI%20Discuss-343434.svg)](https://discuss.circleci.com/c/ecosystem/orbs)
```

2020-04-09 08:11 UTC, lilinor commented on README.md
> +A description of your orb. Utilize this orb to easily add X to your CI/CD pipeline.
```suggestion
Utilize this orb to easily start Genymotion Android virtual device, connect through adb and stop device on [Genymotion Cloud SaaS platform](https://cloud.geny.io) for mobile automation testing.
```

2020-04-09 08:11 UTC, lilinor commented on README.md
> +* Merge to `master` with "`[semver:major]`" in the commit subject to publish 1.0.0 of your orb.
```suggestion
```

2020-04-09 08:11 UTC, lilinor commented on README.md
> +Example use-cases are provided on the orb [registry page](https://circleci.com/orbs/registry/orb/<orb-namespace>/<orb-name>#usage-examples). Source for these examples can be found within the `src/exa
We may also add full blogpost tutorial when we have explaining parallel testing

2020-04-14 16:07 UTC, lilinor commented on src/examples/override-credentials.yml
> +            recipe_uuid: "" # Mandatory: Retrieve the recipe uuid using 'gmsaas recipes list' command line.
```suggestion
            recipe_uuid: "" # Mandatory: Retrieve the recipe uuid using 'gmsaas recipes list' command line or check on https://support.genymotion.com/hc/en-us/articles/360007473658-Supported-Android-devices-templates-for-Genymotion-Cloud-SaaS for comprehensive list of all currently available recipes UUIDs.
```

2020-04-14 16:07 UTC, lilinor commented on src/examples/specify-adb-serial-port.yml
> +            recipe_uuid: "" # Mandatory: Retrieve the recipe uuid using 'gmsaas recipes list' command line.
```suggestion
            recipe_uuid: "" # Mandatory: Retrieve the recipe uuid using 'gmsaas recipes list' command line or check on https://support.genymotion.com/hc/en-us/articles/360007473658-Supported-Android-devices-templates-for-Genymotion-Cloud-SaaS for comprehensive list of all currently available recipes UUIDs.
```

2020-04-14 16:07 UTC, lilinor commented on src/examples/start_stop.yml
> +            recipe_uuid: "" # Mandatory: Retrieve the recipe uuid using 'gmsaas recipes list' command line.
```suggestion
            recipe_uuid: "" # Mandatory: Retrieve the recipe uuid using 'gmsaas recipes list' command line or check on https://support.genymotion.com/hc/en-us/articles/360007473658-Supported-Android-devices-templates-for-Genymotion-Cloud-SaaS for comprehensive list of all currently available recipes UUIDs.
```

2020-04-14 16:07 UTC, lilinor commented on src/examples/override-credentials.yml
> +   - Configure your Genymotion Cloud SaaS account.
```suggestion
   How to :
   - Configure your Genymotion Cloud SaaS account if credentials haven't been set as environment variables or if you wish to override existing credentials.
```

2020-04-14 16:07 UTC, lilinor commented on src/examples/specify-adb-serial-port.yml
> +   - Configure your Genymotion Cloud SaaS account.
```suggestion
   How to :
   - Configure your Genymotion Cloud SaaS account. Credentials are set as environment variables (GMCLOUD_SAAS_EMAIL & GMCLOUD_SAAS_PASSWORD)
```

2020-04-14 16:07 UTC, lilinor commented on src/examples/start_stop.yml
> +   - Configure your Genymotion Cloud SaaS account.
```suggestion
   How to :
   - Configure your Genymotion Cloud SaaS account. Credentials are set as environment variables (GMCLOUD_SAAS_EMAIL & GMCLOUD_SAAS_PASSWORD)
```

2020-04-14 16:07 UTC, lilinor commented on src/commands/start-instance.yml
> +    description: Device template to use. The recipe UUID can be retrieved with command line 'gmsaas recipes list'.
```suggestion
    description: Device template to use. The recipe UUID can be retrieved with command line 'gmsaas recipes list' or check on https://support.genymotion.com/hc/en-us/articles/360007473658-Supported-Android-devices-templates-for-Genymotion-Cloud-SaaS for comprehensive list of all currently available recipes UUIDs.
```

2020-04-16 14:29 UTC, agavignet requested changes

2020-04-16 14:29 UTC, agavignet commented on README.md
> +Utilize this orb to easily start Genymotion Android virtual device, connect through ADB and stop device on [Genymotion Cloud SaaS platform](https://cloud.geny.io) for mobile automation testing.
Genymotion Android virtual device -> Genymotion Cloud SaaS instance ?

2020-04-16 14:29 UTC, agavignet commented on README.md
> +Utilize this orb to easily start Genymotion Android virtual device, connect through ADB and stop device on [Genymotion Cloud SaaS platform](https://cloud.geny.io) for mobile automation testing.
Genymotion Cloud SaaS ~platform~ ?

2020-04-16 14:29 UTC, agavignet commented on README.md
> +To publish a new production version:
Steps to publish a new production version:

2020-04-16 14:29 UTC, agavignet commented on README.md
> +* When ready to publish a new production version, create a PR from `Alpha` to `master`. The Git Subject should include `[semver:patch|minor|release|skip]` to indicate the type of release.
> The Git Subject should include `[semver:patch|minor|release|skip]` to indicate the type of release.

Not sure to understand

2020-04-16 14:29 UTC, agavignet commented on src/@orb.yml
> +  Start Genymotion Android virtual device, connect through ADB and stop device on Genymotion Cloud SaaS platform for mobile automation testing.
Genymotion Cloud SaaS instance
~platform~

2020-04-16 14:29 UTC, agavignet commented on src/commands/start-instance.yml
> +    description: Device template to use. The recipe UUID can be retrieved with command line 'gmsaas recipes list'.
Device template -> Instance recipe

2020-04-16 14:29 UTC, agavignet commented on src/commands/start-instance.yml
> +    description: Device template to use. The recipe UUID can be retrieved with command line 'gmsaas recipes list'.
The recipe UUID can be retrieved -> Recipes can listed

2020-04-16 14:29 UTC, agavignet commented on src/commands/start-instance.yml
> +    type: string
Cannot it be a number?

2020-04-16 14:29 UTC, agavignet commented on src/commands/start-instance.yml
> +          gmsaas instances adbconnect $INSTANCE_UUID --adb-serial-port << parameters.adb_serial_port >>
We can put port options in a variable:
`port_option = --adb-serial-port << parameters.adb_serial_port >>`
To have only one call outside the condition (it's ok if $port_option is empty):
`gmsaas instances adbconnect $INSTANCE_UUID $port_option`

2020-04-16 14:29 UTC, agavignet commented on src/commands/start-instance.yml
> +          gmsaas instances adbconnect $INSTANCE_UUID --adb-serial-port << parameters.adb_serial_port >>
We can put port options in a variable:
`port_option = --adb-serial-port << parameters.adb_serial_port >>`
To have only one call outside the condition (it's ok if $port_option is empty):
`gmsaas instances adbconnect $INSTANCE_UUID $port_option`

2020-04-16 14:29 UTC, agavignet commented on src/commands/stop-instance.yml
> +    description: Instance to stop. The ID of the instance to stop is automatically retrieved. No need to set manually.
The UUID

2020-04-17 12:59 UTC, lilinor commented on README.md
> +Utilize this orb to easily start Genymotion Android virtual device, connect through ADB and stop device on [Genymotion Cloud SaaS platform](https://cloud.geny.io) for mobile automation testing.
> Genymotion Cloud SaaS ~platform~ ?

ok



> Genymotion Android virtual device -> Genymotion Cloud SaaS instance ?

I would like to keep in the description that Genymotion Cloud SaaS instances are indeed Android virtual device, it's more explicit for people who don't know what Genymotion Cloud is.

2020-04-17 12:59 UTC, thomascarpentier commented on README.md
> +To publish a new production version:
The sentence is generated automaticcaly to the starter-kit https://github.com/CircleCI-Public/orb-starter-kit/blob/master/_init/README_TEMPLATE.md. 

I can update if you want, but I don't think it's necessary.

2020-04-17 13:02 UTC, thomascarpentier commented on README.md
> +* When ready to publish a new production version, create a PR from `Alpha` to `master`. The Git Subject should include `[semver:patch|minor|release|skip]` to indicate the type of release.
Don't worry, me too I'm not sure to understand... :smile: 

I guess  when we will publish the new release, some things will be triggered on circleci based on theses information

2020-04-21 09:07 UTC, agavignet approved these changes
One last typo, otherwise good job!

2020-04-21 09:07 UTC, agavignet commented on src/commands/start-instance.yml
> +      Instance recipe to use. Recipes can listed with command line 'gmsaas recipes list',
can **be** listed

2020-04-22 09:45 UTC, merged